service: products

# custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
    apiVersion: 2

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev
functions:
  create:
    handler: ./productHandler.create
    events:
      - http:
          path: products
          method: post
  update:
    handler: ./productHandler.update
    events:
      - http:
          path: products/{id}
          method: put
  find:
    handler: ./productHandler.find
    events:
      - http:
          path: products
          method: get
  findOne:
    handler: ./productHandler.findOne
    events:
      - http:
          path: products/{id}
          method: get

  deleteOne:
    handler: ./productHandler.deleteOne
    events:
      - http:
          path: products/{id}
          method: delete
