service: products

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
    apiVersion: 2

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev
# iamRoleStatements:
#   - Effect: Allow
#     Action:
#       - dynamodb:DescribeTable
#       - dynamodb:Query
#       - dynamodb:Scan
#       - dynamodb:GetItem
#       - dynamodb:PutItem
#       - dynamodb:UpdateItem
#       - dynamodb:DeleteItem
#     # Restrict our IAM role permissions to
#     # the specific table for the stage
#     Resource: '*'
functions:
  create:
    handler: app/modules/products/productHandler.create
    events:
      - http:
          path: products
          method: post
  update:
    handler: app/modules/products/productHandler.update
    events:
      - http:
          path: products/{id}
          method: put
  find:
    handler: app/modules/products/productHandler.find
    events:
      - http:
          path: products
          method: get
  findOne:
    handler: app/modules/products/productHandler.findOne
    events:
      - http:
          path: products/{id}
          method: get

  deleteOne:
    handler: app/modules/products/productHandler.deleteOne
    events:
      - http:
          path: products/{id}
          method: delete
